# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.6.0.20260825"

package:
  name: types-webencodings
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-webencodings/types_webencodings-${{ version }}.tar.gz
  sha256: 06faef4d563d1a2051db7d2985985d53c7e437cde0fe965ff1912a339fa030fe

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      files:
        - site-packages/webencodings-stubs/*.pyi
        - site-packages/webencodings-stubs/__init__.pyi
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script: pip check
about:
  summary: Typing stubs for webencodings
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
